### PR TITLE
Add add-command for Module Class

### PR DESCRIPTION
**Pull request by avock**
Add add-command for Module Class

- Implemented add command to support the Module class
- Update parser to differentiate module and contact commands by adding "m" or "c" after commands

Things to note:

I've commented out two lines of code in ui/MainWindow.java to prevent the initialization error I sent in the group
~~To run add module, change the isValidUrl( ) to return true, still working on the validation regex on that part~~ (UPDATE: fixed)

### CODE REVIEW

**Comment by avock** [comment]
Note: I've commented out these [two lines of code](https://github.com/AY2223S1-CS2103T-W12-1/tp/pull/55/files#:~:text=//moduleListPanel%20%3D%20new%20ModuleListPanel(logic.getFilteredModuleList,//moduleListPanelPlaceholder.getChildren().add(moduleListPanel.getRoot())%3B) to prevent the initialization error I sent in the group

**Review by Effixion — COMMENTED** [review]
LGTM

**Comment by tin-jy** [comment]
Looks good

**Review by tin-jy — APPROVED** [review]
Looks good

**Pull request merged**
